### ISSUE TITLE
能不能指导一下，怎么写lua脚本啊，有点晕

### ISSUE THREAD

**Issue by XL-ZXXZ** [dddyyyjjj/GHUB#1]

**Comment by dddyyyjjj** [comment]
我是跟着b站视频学的，我推荐这个：【随机/循环/按下释放! 罗技GHUB第4期LUA进阶篇! GHUB鼠标驱动功能讲解 G502 G102能用!】 https://www.bilibili.com/video/BV16P4y1M775/?share_source=copy_web&vd_source=10f30b5a470fb1b18418259cb13af4ef

配合ghub里面常用的语句：https://docs.qq.com/sheet/DQ2F2cXN3QktnVmRZ
顺便说一声，ghub脚本编辑器毕竟用的是lua，常见语句里没写的，但是lua能用的也可以写进ghub里运行，比如repeat、until这些。如果有编程基础的话，最快的方法还是对着看现成的脚本，结合上面说的ghub常用语句理解，基本看懂一个脚本后自己也会写了。顺便说一句，如果你要写的脚本里涉及到左键，最好要给脚本设置一个开关， 不然如果出错可能鼠标会乱点或者乱动，会非常麻烦。
如果没有编程基础的话对着最上面的视频看一遍，对于语句逻辑应该也能理解个七七八八，接着就是结合ghub常用语句实战练习了。

**Comment by XL-ZXXZ** [comment]
> 我是跟着b站视频学的，我推荐这个：【随机/循环/按下释放! 罗技GHUB第4期LUA进阶篇! GHUB鼠标驱动功能讲解 G502 G102能用!】 https://www.bilibili.com/video/BV16P4y1M775/?share_source=copy_web&vd_source=10f30b5a470fb1b18418259cb13af4ef
> 
> 配合ghub里面常用的语句：https://docs.qq.com/sheet/DQ2F2cXN3QktnVmRZ 顺便说一声，ghub脚本编辑器毕竟用的是lua，常见语句里没写的，但是lua能用的也可以写进ghub里运行，比如repeat、until这些。如果有编程基础的话，最快的方法还是对着看现成的脚本，结合上面说的ghub常用语句理解，基本看懂一个脚本后自己也会写了。顺便说一句，如果你要写的脚本里涉及到左键，最好要给脚本设置一个开关， 不然如果出错可能鼠标会乱点或者乱动，会非常麻烦。 如果没有编程基础的话对着最上面的视频看一遍，对于语句逻辑应该也能理解个七七八八，接着就是结合ghub常用语句实战练习了。

这个看过，但是想用按键精灵+大漠写一个，不知道怎么搞
